version: '3.9'
services:
  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3010:3010'
    depends_on:
      - portal-gestor-db
    networks:
      - portalGestorNetwork

  portal-gestor-db:
    volumes:
      - portal-gestor-volume:/var/lib/postgresql/data
    container_name: portal-gestor-db
    env_file:
      - .env
    ports:
      - '5432:5432'
    image: 'postgres:latest'
    restart: always
    networks:
      - portalGestorNetwork

networks:
  portalGestorNetwork:
    driver: bridge

volumes:
  portal-gestor-volume:
